name: Nisarg
header-img: mountains.png
collections:
  authors:
    output: true
    permalink: /author/:name/index
menu:
  - id: home
    name: Home
    url: /
  - id: sample-page
    name: Sample Page
    url: /sample-page
  - id: contact
    name: Contact
    url: /contact
paginate: 12
paginate_path: '/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate